modify/seabios: cleaner coding style
same as build/boot/roms

diff --git a/resources/scripts/modify/seabios/configs b/resources/scripts/modify/seabios/configs
--- a/resources/scripts/modify/seabios/configs
+++ b/resources/scripts/modify/seabios/configs
@@ -1,9 +1,8 @@
 #!/usr/bin/env sh
 
-#
 #  helper script: modify coreboot configs (run make menuconfig)
 #
-#	Copyright (C) 2021 Leah Rowe <info@minifree.org>
+#	Copyright (C) 2021, 2023 Leah Rowe <info@minifree.org>
 #
 #	This program is free software: you can redistribute it and/or modify
 #	it under the terms of the GNU General Public License as published by
@@ -17,48 +16,41 @@
 #
 #	You should have received a copy of the GNU General Public License
 #	along with this program.  If not, see <http://www.gnu.org/licenses/>.
-#
-
-# This script assumes that the working directory is the root
-# of git or release archive
 
 [ "x${DEBUG+set}" = 'xset' ] && set -v
 set -u -e
 
-printf "Updating seabios configs\n"
+main()
+{
+	printf "Updating seabios configs\n"
+	download_seabios
+	modify_configs
+}
 
-if [ ! -d "seabios" ]; then
-	./download seabios
-fi
+download_seabios()
+{
+	if [ ! -d "seabios" ]; then
+		./download seabios
+	fi
+	if [ ! -d "seabios" ]; then
+		printf "error: Failed to download SeaBIOS. "
+		printf "Check internet connection?\n"
+		exit 1
+	fi
+}
 
-if [ ! -d "seabios" ]; then
-	printf "error: Failed to download SeaBIOS. check internet connection?\n"
-	exit 1
-fi
+modify_configs()
+{
+	for config in resources/seabios/config/*; do
+		if [ ! -f "${config}" ]; then
+			continue
+		fi
+		make distclean -BC seabios
+		mv "${config}" seabios/.config
+		make menuconfig -BC seabios
+		cp seabios/.config "${config}"
+		make distclean -BC seabios
+	done
+}
 
-for config in resources/seabios/config/*; do
-
-	if [ ! -f "${config}" ]; then continue; fi
-
-	(
-		cd seabios
-		make distclean
-	)
-
-	mv "${config}" seabios/.config
-	(
-		cd seabios
-		make menuconfig
-	)
-
-	cp seabios/.config "${config}"
-
-	(
-		cd seabios
-		make distclean
-	)
-
-done
-
-printf "\n\n"
-
+main $@
