fix "./build help"
thanks Riku Viitanen for pointing out the bug

i b0rked it myself in an earlier revision, while
auditing.

it's funny because i made this exact same mistake
during the last audit, and in the exact same way

it's fixed once again

Signed-off-by: Leah Rowe <leah@libreboot.org>

diff --git a/lbmk b/lbmk
--- a/lbmk
+++ b/lbmk
@@ -33,26 +33,26 @@ main()
 {
 	if [ "${0##*/}" = "lbmk" ]; then
 		die "Do not run the lbmk script directly!"
-	elif [ $# -lt 2 ]; then
+	elif [ $# -lt 1 ]; then
 		die "Too few arguments. Try: ${0} help"
 	fi
 
 	buildpath="./resources/scripts/${0##*/}"
 
 	mode="${1}"
-	if [ "${mode}" = "dependencies" ]; then
-		install_dependencies $@ || die "Could not install dependencies"
-		exit 0
-	fi
 	./.gitcheck
-	[ "${mode}" != "dependencies" ] && \
-		./resources/scripts/misc/versioncheck
 	if [ "${mode}" = help ]; then
 		usage $0
 		exit 0
 	elif [ $# -lt 2 ]; then
 		usage $0
 		exit 0
+	fi
+	if [ "${mode}" = "dependencies" ]; then
+		install_dependencies $@ || die "Could not install dependencies"
+		exit 0
+	else
+		./resources/scripts/misc/versioncheck
 	fi
 
 	option="${2}"
