scripts: better handling of printf: stdout/stderr
in some cases, messages that should be considered errors
or warnings, were being written to the standard output,
rather than written as error messages.

also: one or two printf statements should specifically
avoid printing errors (to any file); in these cases,
stdout has been redirected to /dev/null

Signed-off-by: Leah Rowe <leah@libreboot.org>

diff --git a/lbmk b/lbmk
--- a/lbmk
+++ b/lbmk
@@ -86,7 +86,7 @@ main()
 			fail "Invalid mode '${mode}'. Run: ${0} help"
 		elif [ ! -f "${buildpath}/${mode}/${option}" ]; then
 			usage $0
-			printf "Invalid option for '%s'." ${mode}
+			printf "Invalid option for '%s'." ${mode} 1>&2
 			fail "Run: ${0} ${mode} list'."
 		fi
 		"${buildpath}/${mode}/${option}" $@ || fail "lbmk error"
