NEW MAINBOARD: HP EliteBook 820 G2
This is of Broadwell platform, one generation above Haswell.

Of note: this uses HP Sure Start. Although the flash is 16MB,
our CBFS section (and IFD configuration) assumes 12MB flash,
so the final 4MB will be left unflashed on installation,
after blanking the private flash. The coreboot documents have
more information about this.

Some minor design changes in lbmk were made, to accomodate
this port:

Support for extracting refcode binaries added (pulled from
Google recovery images). The refcode file is an ELF that
initialises the MRC and the PCH. It is also responsible for
enabling or disabling the Intel GbE device, where Google
does not enable it, but lbmk modifies it per the instructions
on the coreboot documentation, so as to enable Intel GbE.

Google's recovery image stores the refcode as a stage file,
but coreboot changed the format (for CBFS files) after 4.13
so coreboot 4.13's cbfstool is used to extract refcode. This
realisation made me also change the script logic to use a
cbfstool and ifdtool version matching the coreboot tree, for
all parts of lbmk, whereas lbmk previously used only the
default tree for cbfstool/ifdtool, on insertion and deletion
of vendor files - it was 81dc20e744 that broke extraction of
refcode on google's recovery images, where google used an older
version of cbfstool to insert the files in their coreboot ROMs.
A further backported patch has been added, copying coreboot
revision f22f408956 which is a build fix from Nico Huber.

Iru Cai submitted an ACPI bugfix after the revision lbmk
currently uses, for coreboot/default, and this fix is
needed for rebooting to work on Linux 6.1 or higher. This
patch has been backported to lbmk, while it still uses the
same October 2023 revision of coreboot.

Broadwell MRC is inserted at the same offset as Haswell,
so I didn't need to tweak that.

Signed-off-by: Leah Rowe <leah@libreboot.org>

diff --git a/script/vendor/inject b/script/vendor/inject
--- a/script/vendor/inject
+++ b/script/vendor/inject
@@ -2,14 +2,14 @@
 # SPDX-License-Identifier: GPL-3.0-only
 # SPDX-FileCopyrightText: 2022 Caleb La Grange <thonkpeasant@protonmail.com>
 # SPDX-FileCopyrightText: 2022 Ferass El Hafidi <vitali64pmemail@protonmail.com>
-# SPDX-FileCopyrightText: 2023 Leah Rowe <leah@libreboot.org>
+# SPDX-FileCopyrightText: 2023-2024 Leah Rowe <leah@libreboot.org>
 
 . "include/err.sh"
 . "include/option.sh"
 
 nvmutil="util/nvmutil/nvm"
 
-eval "$(setvars "" archive rom modifygbe nukemode release new_mac)"
+eval "$(setvars "" archive rom modifygbe nukemode release new_mac tree)"
 
 main()
 {
@@ -51,7 +51,11 @@ check_board()
 	fi
 
 	boarddir="${cbcfgsdir}/${board}"
-	[ -d "$boarddir" ] || err "check_board: board $board missing"; return 0
+	[ -d "$boarddir" ] || err "check_board: board $board missing"
+	[ -f "$boarddir/target.cfg" ] || \
+		err "check_board $board: target.cfg missing"
+	. "$boarddir/target.cfg" 2>/dev/null
+	[ -z "$tree" ] && err "check_board $board: tree undefined"; return 0
 }
 
 check_release()
@@ -84,9 +88,12 @@ detect_board()
 
 build_dependencies()
 {
-	[ -d "${cbdir}" ] || x_ ./update trees -f coreboot default
+	cbdir="src/coreboot/$tree"
+	cbfstool="cbutils/$tree/cbfstool"
+	ifdtool="cbutils/$tree/ifdtool"
+	[ -d "${cbdir}" ] || x_ ./update trees -f coreboot $tree
 	if [ ! -f "${cbfstool}" ] || [ ! -f "${ifdtool}" ]; then
-		x_ ./update trees -b coreboot utils default
+		x_ ./update trees -b coreboot utils $tree
 	fi
 	[ -z "$new_mac" ] || [ -f "$nvmutil" ] || x_ make -C util/nvmutil
 	[ "$nukemode" = "nuke" ] || x_ ./vendor download $board; return 0
@@ -144,6 +151,8 @@ patch_rom()
 
 	[ "$CONFIG_HAVE_MRC" = "y" ] && \
 		inject "mrc.bin" "${CONFIG_MRC_FILE}" "mrc" "0xfffa0000"
+	[ -n "$CONFIG_HAVE_REFCODE_BLOB" ] && \
+		inject "fallback/refcode" "$CONFIG_REFCODE_BLOB_FILE" "stage"
 	[ "${CONFIG_HAVE_ME_BIN}" = "y" ] && \
 		inject "IFD" "${CONFIG_ME_BIN_PATH}" "me"
 	[ "${CONFIG_KBC1126_FIRMWARE}" = "y" ] && \
@@ -200,9 +209,14 @@ inject()
 		fi
 	else
 		if [ "${nukemode}" != "nuke" ]; then
-			"$cbfstool" "$rom" add -f "$_dest" \
-			    -n "$cbfsname" -t $_t $_offset || \
-			    err "inject $rom: can't insert $_t file $_dest"
+			if [ "$_t" = "stage" ]; then # broadwell refcode
+				"$cbfstool" "$rom" add-stage -f "$_dest" \
+				    -n "$cbfsname" -t stage -c lzma
+			else
+				"$cbfstool" "$rom" add -f "$_dest" \
+				    -n "$cbfsname" -t $_t $_offset || \
+				    err "$rom: can't insert $_t file $_dest"
+			fi
 		else
 			"$cbfstool" "$rom" remove -n "$cbfsname" || \
 			    err "inject $rom: can't remove $cbfsname"
