remove download scripts, consolidate into script
most of them were just calling the gitclone script,
so remove them.

the grub script was treating gnulib as a dependency.
i've now added the ability to grab 1 dependency, in
the gitclone script (it should be expanded later to
support multiple dependencies)

the gitclone script has been renamed to "fetch".
the "fetch_trees" script does more or less the same
thing, but calls "fetch" and handles multiple revisions
if a project needs that

this is more efficient, and slightly reduces the code
size of lbmk!

Signed-off-by: Leah Rowe <leah@libreboot.org>

diff --git a/resources/scripts/build/module/uefitool b/resources/scripts/build/module/uefitool
--- a/resources/scripts/build/module/uefitool
+++ b/resources/scripts/build/module/uefitool
@@ -24,7 +24,7 @@ set -u -e
 main()
 {
 	if [ ! -d "uefitool" ]; then
-		./download uefitool || fail "cannot download uefitool"
+		./fetch uefitool || fail "cannot download uefitool"
 	fi
 
 	printf "Building uefitool (UEFIExtract)\n"
diff --git a/resources/scripts/update/blobs/download b/resources/scripts/update/blobs/download
--- a/resources/scripts/update/blobs/download
+++ b/resources/scripts/update/blobs/download
@@ -184,7 +184,7 @@ build_dependencies()
 {
 	if [ ! -d me_cleaner ]; then
 		printf "downloading me_cleaner\n"
-		./download me_cleaner || fail "could not download me_cleaner"
+		./fetch me_cleaner || fail "could not download me_cleaner"
 	fi
 	if [ ! -d ${cbdir} ]; then
 		printf "downloading coreboot\n"
@@ -193,17 +193,17 @@ build_dependencies()
 	fi
 	if [ ! -d bios_extract ]; then
 		printf "downloading bios_extract\n"
-		./download bios_extract \
+		./fetch bios_extract \
 				|| fail "could not download bios_extract"
 	fi
 	if [ ! -d biosutilities ]; then
 		printf "downloading biosutilities\n"
-		./download biosutilities \
+		./fetch biosutilities \
 				|| fail "could not download biosutilities"
 	fi
 	if [ ! -d uefitool ]; then
 		printf "download uefitool (for UEFIExtract)\n"
-		./download uefitool \
+		./fetch uefitool \
 				|| fail "could not download uefitool"
 	fi
 	if [ ! -f uefitool/uefiextract ]; then
@@ -239,7 +239,7 @@ download_blobs()
 			download_e6400vga || _failed="${_failed} e6400vga"
 			;;
 		*MRC*)
-			./download mrc || _failed="${_failed} mrc"
+			./update blobs mrc || _failed="${_failed} mrc"
 			;;
 		esac
 	done
diff --git a/resources/scripts/update/blobs/extract b/resources/scripts/update/blobs/extract
--- a/resources/scripts/update/blobs/extract
+++ b/resources/scripts/update/blobs/extract
@@ -58,10 +58,10 @@ build_dependencies()
 {
 	if [ ! -d me_cleaner ]; then
 		printf "downloading me_cleaner\n"
-		./download me_cleaner || fail 'could not download me_cleaner'
+		./fetch me_cleaner || fail 'could not download me_cleaner'
 	else
 		printf "me_cleaner already downloaded. Skipping.\n"
-		printf "run ./download me_cleaner to manually overwrite\n"
+		printf "run ./fetch me_cleaner to manually overwrite\n"
 	fi
 
 	if [ ! -d ${cbdir} ]; then
@@ -90,7 +90,7 @@ extract_blobs()
 
 	if [ "$CONFIG_HAVE_MRC" = "y" ]; then
 		printf 'haswell board detected, downloading mrc\n'
-		./download mrc || fail "could not download mrc"
+		./update blobs mrc || fail "could not download mrc"
 	fi
 
 	_me_destination=${CONFIG_ME_BIN_PATH#../../}
