blobutil/ec: abort if kbc1126 ec extraction fails
This was an oversight on my part.

Should extraction fail, we must abort. This is in preparation
for addition of future mainboards, where further tweaking is
required in blobutil. This error check will warn us about it.

Signed-off-by: Leah Rowe <leah@libreboot.org>

diff --git a/resources/scripts/update/blobs/download b/resources/scripts/update/blobs/download
--- a/resources/scripts/update/blobs/download
+++ b/resources/scripts/update/blobs/download
@@ -337,6 +337,11 @@ extract_ec()
 		unar -D ROM.CAB Rom.bin
 		mv Rom.bin ec.bin
 	fi
+	if [ ! -f ec.bin ]; then
+		printf "could not extract ec.bin for board '%s'" ${board} \
+			1>&2
+		fail "aborting the build. please audit blobutil carefully."
+	fi
 
 	"${kbc1126_ec_dump}" ec.bin
 	)
