scripts: put quotes around file/directory names
Signed-off-by: Leah Rowe <leah@libreboot.org>

diff --git a/resources/scripts/build/boot/roms_helper b/resources/scripts/build/boot/roms_helper
--- a/resources/scripts/build/boot/roms_helper
+++ b/resources/scripts/build/boot/roms_helper
@@ -189,7 +189,7 @@ if [ "${payload_grub}" = "y" ] || \
 		printf "Required GRUB payloads not yet built. Building now.\n" \
 		    1>&2
 	fi
-	for keymapfile in ${kmapdir}/*; do
+	for keymapfile in "${kmapdir}"/*; do
 		[ -f "${keymapfile}" ] || continue
 
 		keymap="${keymapfile##*/}"
@@ -230,11 +230,11 @@ moverom() {
 	printf "\nCreating new ROM image: %s\n" "${newrompath}"
 
 	if [ "${cuttype}" = "4MiB IFD BIOS region" ]; then
-		dd if=${rompath} of=${newrompath} bs=1 \
-		    skip=$(($(stat -c %s ${rompath}) - 0x400000)) \
+		dd if="${rompath}" of="${newrompath}" bs=1 \
+		    skip=$(($(stat -c %s "${rompath}") - 0x400000)) \
 		    count=4194304 || err "moverom: cannot cut 4MB section"
 	else
-		cp ${rompath} ${newrompath} || err "moverom: cannot copy rom"
+		cp "${rompath}" "${newrompath}" || err "moverom: can't copy rom"
 	fi
 
 	# pike2008 cards cause a system hang when loading option roms in seabios
@@ -245,7 +245,7 @@ moverom() {
 		touch "${emptyrom}" || err "cannot create fake oprom"
 		for deviceID in "0072" "3050"; do
 			"${cbfstool}" "${newrompath}" add -f "${emptyrom}" \
-			    -n pci1000,${deviceID}.rom -t raw || \
+			    -n "pci1000,${deviceID}.rom" -t raw || \
 			    err "moverom: cannot insert fake pike2008 rom"
 		done
 		rm -f "${emptyrom}" || err "moverom: cannot remove pike2008 rom"
@@ -257,7 +257,7 @@ moverom() {
 			[ -f "${ifdgbe}" ] || \
 				./build descriptors ich9m || \
 				    err "moverom: cannot create ich9m ifd"
-			dd if=${ifdgbe} of=${newrompath} bs=1 count=12k \
+			dd if="${ifdgbe}" of="${newrompath}" bs=1 count=12k \
 			    conv=notrunc || err "moverom: cant insert ich9m ifd"
 		fi
 		cmpstr="${romsize}MiB ICH9 IFD NOGBE NOR flash"
@@ -266,18 +266,19 @@ moverom() {
 			[ -f "${ifdgbe}" ] || \
 				./build descriptors ich9m || \
 				    err "moverom: cannot create ich9m ifd"
-			dd if=${ifdgbe} of=${newrompath} bs=1 count=4k \
+			dd if="${ifdgbe}" of="${newrompath}" bs=1 count=4k \
 			    conv=notrunc || err "moverom: cant insert ich9m ifd"
 		fi
 	done
 
 	if [ "${cuttype}" = "i945 laptop" ]; then
-		dd if=${newrompath} of=top64k.bin bs=1 \
-		    skip=$(($(stat -c %s ${newrompath}) - 0x10000)) count=64k \
-		    || err "moverom: cannot copy boot block from i945 rom"
-		dd if=top64k.bin of=${newrompath} bs=1 \
-		    seek=$(($(stat -c %s ${newrompath}) - 0x20000)) count=64k \
-		    conv=notrunc || \
+		dd if="${newrompath}" of=top64k.bin bs=1 \
+		    skip=$(($(stat -c %s "${newrompath}") - 0x10000)) \
+		    count=64k || \
+		    err "moverom: cannot copy boot block from i945 rom"
+		dd if=top64k.bin of="${newrompath}" bs=1 \
+		    seek=$(($(stat -c %s "${newrompath}") - 0x20000)) \
+		    count=64k conv=notrunc || \
 		    err "moverom: cannot copy boot block into i945 rom"
 		rm -f top64k.bin || err "moverom: can't remove top64k.bin"
 	fi
@@ -292,7 +293,7 @@ moverom() {
 		if [ "${microcode_present}" = "n" ]; then
 			rm -f "${_newrom_b}" || err "cannot remove ${_newrom_b}"
 			printf "REMARK: '%s' already lacks microcode\n" \
-			    ${newrompath}
+			    "${newrompath}"
 			printf "Renaming default ROM file instead.\n"
 			mv "${newrompath}" "${_newrom_b}" || \
 			    err "moverom: mv \"${newrompath}\" \"${_newrom_b}\""
@@ -520,7 +521,7 @@ mkRoms()
 
 	if [ "${payload_memtest}" = "y" ]; then
 		"${cbfstool}" "${corebootrom}" add-payload \
-		    -f ${memtest_bin} -n img/memtest -c lzma || \
+		    -f "${memtest_bin}" -n img/memtest -c lzma || \
 		    err "mkRoms: cannot add img/memtest to coreboot rom"
 	fi
 
diff --git a/resources/scripts/update/blobs/download b/resources/scripts/update/blobs/download
--- a/resources/scripts/update/blobs/download
+++ b/resources/scripts/update/blobs/download
@@ -79,7 +79,7 @@ main()
 detect_firmware()
 {
 	set -- "${boarddir}/config/"*
-	. ${1} 2>/dev/null
+	. "${1}"
 	. "${boarddir}/target.cfg"
 
 	[ "${CONFIG_HAVE_MRC}" = "y" ] && needs="${needs} MRC"
@@ -94,7 +94,7 @@ detect_firmware()
 	[ -z ${needs+x} ] && \
 		printf "No binary blobs needed for this board\n" && \
 		return 1
-	printf "Firmware needed for board '%s':\n%s\n" ${board} ${needs}
+	printf "Firmware needed for board '%s':\n%s\n" "${board}" "${needs}"
 }
 
 scan_sources_config()
@@ -167,8 +167,8 @@ build_dependencies()
 	[ -f uefitool/uefiextract ] || \
 		./build src for -b uefitool || \
 		    err "build_dependencies: can't build uefitool"
-	if [ ! -f ${cbdir}/util/kbc1126/kbc1126_ec_dump ]; then
-		make -BC ${cbdir}/util/kbc1126 || \
+	if [ ! -f "${cbdir}/util/kbc1126/kbc1126_ec_dump" ]; then
+		make -BC "${cbdir}/util/kbc1126" || \
 		    err "build_dependencies: can't build kbc1126_ec_dump"
 	fi
 }
@@ -210,7 +210,7 @@ extract_blob_intel_me()
 	_me_destination=${CONFIG_ME_BIN_PATH#../../}
 
 	[ -d "${_me_destination%/*}" ] || \
-		mkdir -p ${_me_destination%/*} || \
+		mkdir -p "${_me_destination%/*}" || \
 		    err "extract_blob_intel_me: mkdir ${_me_destination%/*}"
 	[ ! -d "${appdir}" ] || \
 		rm -Rf "${appdir}" || \
@@ -222,8 +222,8 @@ extract_blob_intel_me()
 
 	printf "Extracting and stripping Intel ME firmware\n"
 
-	innoextract ${dl_path} -d ${appdir} || \
-	    7z x ${dl_path} -o${appdir} || \
+	innoextract "${dl_path}" -d "${appdir}" || \
+	    7z x "${dl_path}" -o"${appdir}" || \
 	    unar "${dl_path}" -o "${appdir}" || \
 	    err "extract_blob_intel_me: could not extract vendor update"
 
@@ -265,11 +265,11 @@ bruteforce_extract_blob_intel_me()
 			    && break # (we found me.bin)	
 			"${mecleaner}" -r -t -O "${_me_destination}" "${i}" \
 			    && break # (we found me.bin)
-			"${me7updateparser}" -O ${_me_destination} "${i}" \
+			"${me7updateparser}" -O "${_me_destination}" "${i}" \
 			    && break # (we found me.bin)
 			_7ztest="${_7ztest}a"
-			7z x "${i}" -o${_7ztest} \
-			    || innoextract "${i}" -d  "${_7ztest}" \
+			7z x "${i}" -o"${_7ztest}" \
+			    || innoextract "${i}" -d "${_7ztest}" \
 			    || unar "${i}" -o "${_7ztest}" \
 			    || continue
 			bruteforce_extract_blob_intel_me "${_me_destination}" \
@@ -368,10 +368,10 @@ extract_e6400vga()
 		return 0
 	fi
 	[ -d "${_vga_destination%/*}" ] || \
-		mkdir -p ${_vga_destination%/*} || \
+		mkdir -p "${_vga_destination%/*}" || \
 		    err "extract_e6400vga: can't mkdir ${_vga_destination%/*}"
 	[ ! -d "${appdir}" ] || \
-		rm -Rf ${appdir} || \
+		rm -Rf "${appdir}" || \
 		    err "extract_e6400vga: can't rm -Rf ${appdir}"
 
 	mkdir -p "${appdir}" || \
@@ -482,18 +482,18 @@ fetch_update()
 	[ -z "${dl_url+x}" ] && [ "${fw_type}" != "e6400vga" ] && \
 		err "fetch_update ${fw_type}: dl_url unspecified for: ${board}"
 
-	dl_path=${blobdir}/cache/${dlsum}
-	mkdir -p ${blobdir}/cache || err "fetch_update: !mkdir ${blobdir}/cache"
+	dl_path="${blobdir}/cache/${dlsum}"
+	mkdir -p "${blobdir}/cache" || err "fetch_update: !mkdir ${blobdir}/cache"
 
 	dl_fail="y"
-	vendor_checksum ${dlsum} && dl_fail="n"
+	vendor_checksum "${dlsum}" && dl_fail="n"
 	for x in "${dl}" "${dl_bkup}"; do
 		[ "${dl_fail}" = "n" ] && break
 		[ -z "${x}" ] && continue
 		rm -f "${dl_path}" || \
 		    err "fetch_update ${fw_type}: !rm -f ${dl_path}"
-		wget -U "${agent}" ${x} -O ${dl_path} || continue
-		vendor_checksum ${dlsum} && dl_fail="n"
+		wget -U "${agent}" "${x}" -O "${dl_path}" || continue
+		vendor_checksum "${dlsum}" && dl_fail="n"
 	done
 	if [ "${dl_fail}" = "y" ]; then
 		printf "ERROR: invalid vendor updates for: %s\n" "${board}" 1>&2
@@ -504,10 +504,11 @@ fetch_update()
 vendor_checksum()
 {
 	if [ ! -f "${dl_path}" ]; then
-		printf "Vendor update not found on disk for: %s\n" ${board} 1>&2
+		printf "Vendor update not found on disk for: %s\n" "${board}" \
+		    1>&2
 		return 1
 	elif [ "$(sha1sum ${dl_path} | awk '{print $1}')" != "${1}" ]; then
-		printf "Bad checksum on vendor update for: %s\n" ${board} 1>&2
+		printf "Bad checksum on vendor update for: %s\n" "${board}" 1>&2
 		return 1
 	fi
 }
diff --git a/resources/scripts/update/blobs/inject b/resources/scripts/update/blobs/inject
--- a/resources/scripts/update/blobs/inject
+++ b/resources/scripts/update/blobs/inject
@@ -72,7 +72,7 @@ main()
 
 check_board()
 {
-	if ! check_release ${archive} ; then
+	if ! check_release "${archive}" ; then
 		[ -f "${rom}" ] || \
 			err "check_board: \"${rom}\" is not a valid path"
 		[ -z ${rom+x} ] && \
@@ -102,7 +102,7 @@ check_release()
 # It will only succeed if the filename is not changed from the build/download
 detect_board()
 {
-	path=${1}
+	path="${1}"
 	filename=$(basename ${path})
 	case ${filename} in
 	grub_*)
@@ -146,20 +146,20 @@ patch_release_roms()
 	tar xf "${releasearchive}" -C "${_tmpdir}" || \
 	    err "patch_release_roms: could not extract release archive"
 
-	for x in ${_tmpdir}/bin/*/*.rom ; do
+	for x in "${_tmpdir}"/bin/*/*.rom ; do
 		echo "patching rom $x"
-		patch_rom ${x} || err "patch_release_roms: could not patch ${x}"
+		patch_rom "${x}" || err "patch_release_roms: could not patch ${x}"
 	done
 
 	(
-	cd ${_tmpdir}/bin/*
+	cd "${_tmpdir}"/bin/*
 	sha1sum --status -c blobhashes || \
 	    err "patch_release_roms: ROMs did not match expected hashes"
 	)
 
 	if [ "${modifygbe}" = "true" ]; then
-		for x in ${_tmpdir}/bin/*/*.rom ; do
-			modify_gbe ${x}
+		for x in "${_tmpdir}"/bin/*/*.rom ; do
+			modify_gbe "${x}"
 		done
 	fi
 
@@ -203,7 +203,7 @@ patch_rom()
 	    [ "${CONFIG_SMSC_SCH5545_EC_FW_FILE}" != "" ] && \
 		inject_blob_smsc_sch5545_ec "${rom}"
 	[ "${modifygbe}" = "true" ] && ! [ "${release}" = "true" ] && \
-		modify_gbe ${rom}
+		modify_gbe "${rom}"
 
 	printf "ROM image successfully patched: %s\n" "${rom}"
 }
@@ -232,7 +232,7 @@ inject_blob_intel_mrc()
 	# source code, and it is *always* correct for haswell platform.
 	# TODO: this logic should be tweaked to handle more platforms
 
-	${cbfstool} ${rom} add -f mrc/haswell/mrc.bin -n mrc.bin -t mrc \
+	"${cbfstool}" "${rom}" add -f mrc/haswell/mrc.bin -n mrc.bin -t mrc \
 	    -b 0xfffa0000 || err "inject_blob_intel_mrc: cannot insert mrc.bin"
 }
 
@@ -248,7 +248,7 @@ inject_blob_intel_me()
 	[ ! -f "${_me_location}" ] && \
 		err "inject_blob_intel_me: per CONFIG_ME_BIN_PATH: file missing"
 
-	${ifdtool} -i me:${_me_location} ${rom} -O ${rom} || \
+	"${ifdtool}" -i me:"${_me_location}" "${rom}" -O "${rom}" || \
 	    err "inject_blob_intel_me: cannot insert me.bin"
 }
 
@@ -273,10 +273,10 @@ inject_blob_hp_kbc1126_ec()
 		err "inject_blob_hp_kbc1126_ec: ${board}: ecfw not downloaded"
 	fi
 
-	${cbfstool} "${rom}" add -f ${_ec1_location} -n ecfw1.bin \
+	"${cbfstool}" "${rom}" add -f "${_ec1_location}" -n ecfw1.bin \
 	    -b ${_ec1_offset} -t raw || \
 	    err "inject_blob_hp_kbc1126_ec: cannot insert ecfw1.bin"
-	${cbfstool} "${rom}" add -f ${_ec2_location} -n ecfw2.bin \
+	"${cbfstool}" "${rom}" add -f "${_ec2_location}" -n ecfw2.bin \
 	    -b ${_ec2_offset} -t raw || \
 	    err "inject_blob_hp_kbc1126_ec: cannot insert ecfw2.bin"
 }
@@ -298,7 +298,7 @@ inject_blob_dell_e6400_vgarom_nvidia()
 		err "inject_blob_dell_e6400vga: ${_vga_location} doesn't exist"
 	fi
 
-	${cbfstool} ${rom} add -f "${_vga_location}" \
+	"${cbfstool}" "${rom}" add -f "${_vga_location}" \
 	    -n "pci${CONFIG_VGA_BIOS_ID}.rom" -t optionrom || \
 	    err "inject_blob_dell_e6400vga: cannot insert vga oprom"
 }
@@ -322,7 +322,7 @@ modify_gbe()
 {
 	printf "changing mac address in gbe to ${new_mac}\n"
 
-	rom=${1}
+	rom="${1}"
 
 	[ -z ${CONFIG_GBE_BIN_PATH} ] && \
 		err "modify_gbe: ${board}: CONFIG_GBE_BIN_PATH not set"
@@ -331,27 +331,27 @@ modify_gbe()
 
 	[ -f "${_gbe_location}" ] || \
 		err "modify_gbe: CONFIG_GBE_BIN_PATH points to missing file"
-	[ -f ${nvmutil} ] || \
+	[ -f "${nvmutil}" ] || \
 		make -C util/nvmutil || err "modify_gbe: couldn't build nvmutil"
 
 	_gbe_tmp=$(mktemp -t gbeXXXX.bin)
-	cp ${_gbe_location} ${_gbe_tmp}
-	${nvmutil} "${_gbe_tmp}" setmac "${new_mac}" || \
+	cp "${_gbe_location}" "${_gbe_tmp}"
+	"${nvmutil}" "${_gbe_tmp}" setmac "${new_mac}" || \
 	    err "modify_gbe: ${board}: failed to modify mac address"
 
-	${ifdtool} -i GbE:${_gbe_tmp} "${rom}" -O "${rom}" || \
+	"${ifdtool}" -i GbE:"${_gbe_tmp}" "${rom}" -O "${rom}" || \
 	    err "modify_gbe: ${board}: cannot insert modified gbe.bin"
 
-	rm -f ${_gbe_tmp}
+	rm -f "${_gbe_tmp}"
 }
 
 listboards()
 {
-	for boarddir in ${cbcfgsdir}/*; do
+	for boarddir in "${cbcfgsdir}"/*; do
 		[ -d "${boarddir}" ] || continue
 		board="${boarddir##${cbcfgsdir}/}"
 		board="${board%/}"
-		printf '%s\n' "${board##*/}"
+		printf "%s\n" "${board##*/}"
 	done
 }
 
