use the new coding style in scripts
there were stragglers left over from the last audit,
and these stragglers still exist even after all the
major re-factoring as of late

the new style is: bsd-like coding style and error
handling. verbose yet simple error handling. we use
an "err" function in a way reminiscent of most C
programs that you see in openbsd base (err.h)

this style is very clean, resulting in readable code

Signed-off-by: Leah Rowe <leah@libreboot.org>

diff --git a/resources/scripts/build/clean/cbutils b/resources/scripts/build/clean/cbutils
--- a/resources/scripts/build/clean/cbutils
+++ b/resources/scripts/build/clean/cbutils
@@ -24,26 +24,36 @@
 [ "x${DEBUG+set}" = 'xset' ] && set -v
 set -u -e
 
-# clean coreboot utilities (dependencies for 'build'):
+. "include/err.sh"
 
-printf "Cleaning the previous build of coreboot and its utilities\n"
+main()
+{
+	printf "Cleaning the previous build of coreboot and its utilities\n"
 
-rm -Rf cbutils
+	rm -Rf cbutils || err "cannot remove cbutils/"
+	[ ! -d "coreboot/" ] && exit 0
 
-[ ! -d "coreboot/" ] && exit 0
+	clean_cbutils
+}
 
-for tree in coreboot/*; do
-	[ "${tree##*/}" = "coreboot" ] && continue
-	[ -d "${tree}" ] || continue
+clean_cbutils()
+{
+	for tree in coreboot/*; do
+		[ "${tree##*/}" = "coreboot" ] && continue
+		[ -d "${tree}" ] || continue
 
-	# Clean coreboot, of course
-	make -C "${tree}/" distclean
+		# Clean coreboot, of course
+		make -C "${tree}/" distclean || \
+		    err "cannot distclean coreboot tree, ${tree}"
 
-	# Clean its utilities as well
-	for util in cbfstool ifdtool nvramtool cbmem; do
-		make distclean -C "${tree}/util/${util}/"
+		# Clean its utilities as well
+		for util in cbfstool ifdtool nvramtool cbmem; do
+			make distclean -C "${tree}/util/${util}/" || \
+			    err "cannot clean util, ${util}, at ${tree}"
+		done
+		make distclean -C "${tree}/payloads/libpayload/" || \
+		    err "cannot distclean libpayload, at ${tree}"
 	done
-	make distclean -C "${tree}/payloads/libpayload/"
-done
+}
 
-printf "\n\n"
+main $@
diff --git a/resources/scripts/build/clean/seabios b/resources/scripts/build/clean/seabios
--- a/resources/scripts/build/clean/seabios
+++ b/resources/scripts/build/clean/seabios
@@ -2,7 +2,7 @@
 
 #  helper script: clean the dependencies that were built in seabios
 #
-#	Copyright (C) 2015, 2020, 2021 Leah Rowe <info@minifree.org>
+#	Copyright (C) 2015,2020,2021,2023 Leah Rowe <info@minifree.org>
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -26,13 +26,22 @@ set -u -e
 # clean bucts
 # --------------------------------------------------------
 
-printf "Cleaning the previous builds of seabios\n"
+main()
+{
+	[ ! -d "elf/seabios" ] || rm -Rf elf/seabios || \
+	    err "cannot remove elf/seabios"
+	[ ! -d "seabios/" ] && exit 0
 
-[ ! -d "elf/seabios" ] || rm -Rf elf/seabios || err "cannot remove elf/seabios"
-[ ! -d "seabios/" ] && exit 0
+	clean_seabios
+}
 
-for x in seabios/*; do
-	[ "${x}" = "seabios/seabios" ] && continue
-	[ ! -d "${x}" ] && continue
-	make -C "${x}" distclean || err "cannot distclean tree, ${x}"
-done
+clean_seabios()
+{
+	for x in seabios/*; do
+		[ ! -d "${x}" ] && continue
+		[ "${x}" = "seabios/seabios" ] && continue
+		make -C "${x}" distclean || err "cannot distclean tree, ${x}"
+	done
+}
+
+main $@
diff --git a/resources/scripts/build/coreboot/utils b/resources/scripts/build/coreboot/utils
--- a/resources/scripts/build/coreboot/utils
+++ b/resources/scripts/build/coreboot/utils
@@ -21,10 +21,12 @@
 [ "x${DEBUG+set}" = 'xset' ] && set -v
 set -u -e
 
-printf "Building coreboot utils\n"
+. "include/err.sh"
 
 main()
 {
+	printf "Building coreboot utils\n"
+
 	if [ $# -gt 0 ]; then
 		for board in "${@}"; do
 			build_for_mainboard ${board} || \
@@ -45,28 +47,28 @@ build_for_mainboard() {
 	[ -f "resources/coreboot/${board}/target.cfg" ] || continue
 	tree="undefined"
 	. "resources/coreboot/${board}/target.cfg" # source
-	if [ "${tree}" = "undefined" ]; then
-		printf "build/cbutils: improper tree definition for '%s'" \
-				"${board}"
-		return 1
-	fi
-	buildutils "${tree}" || return 1
+	[ "${tree}" = "undefined" ] && \
+		err "build/cbutils: improper tree definition for '${board}'"
+	buildutils "${tree}"
 }
 
 buildutils() {
 	tree="${1}"
 	[ -d "coreboot/${tree}/" ] || \
-		./fetch_trees coreboot $tree || return 1
+		./fetch_trees coreboot $tree || \
+		    err "cannot fetch ${tree}"
 	for util in cbfstool ifdtool; do
 		[ -f "cbutils/${tree}/${util}" ] && continue
 		[ -d "cbutils/${tree}" ] || \
-			mkdir -p "cbutils/${tree}" || return 1
+			mkdir -p "cbutils/${tree}" || \
+			    err "cannot create directory, cbutils/${tree}"
 
 		utildir="coreboot/${tree}/util/${util}"
-		make distclean -C "${utildir}" || return 1
-		make -j$(nproc) -C "${utildir}" || return 1
-		mv "${utildir}/${util}" "cbutils/${tree}" || return 1
-		make distclean -C "${utildir}" || return 1
+		make distclean -C "${utildir}" || err "cannot clean ${utildir}"
+		make -j$(nproc) -C "${utildir}" || err "cannot build ${utildir}"
+		cp "${utildir}/${util}" "cbutils/${tree}" || \
+		    err "cannot copy util, ${util}, to cbutils/${tree}/"
+		make distclean -C "${utildir}" || err "can't clean ${utildir}"
 	done
 }
 
