curl/wget downloads: set re-try count to 3
explicitly set the count to 3, so that a maximum of 3
attemps are made per download, barring fatal errors such
as http 404.

Signed-off-by: Leah Rowe <leah@libreboot.org>

diff --git a/script/update/blobs/mrc b/script/update/blobs/mrc
--- a/script/update/blobs/mrc
+++ b/script/update/blobs/mrc
@@ -111,7 +111,7 @@ download_image()
 	_sha1sum=${3}
 
 	printf "Downloading recovery image\n"
-	curl "$url" > "$_file.zip" || err "download_image: curl failed"
+	curl --retry 3 "$url" > "$_file.zip" || err "download_image: curl failed"
 	printf "Verifying recovery image checksum\n"
 	if [ "$(sha1sum "${_file}.zip" | awk '{print $1}')" = "${_sha1sum}" ]
 	then
