trees: better skip-clean string in handle_src_tree
Signed-off-by: Leah Rowe <leah@libreboot.org>

diff --git a/script/trees b/script/trees
--- a/script/trees
+++ b/script/trees
@@ -139,7 +139,7 @@ handle_src_tree()
 	if [ ! -d "$cdir" ]; then
 		if [ "$mode" = "distclean" ] || \
 		    [ "$mode" = "crossgcc-clean" ]; then
-			printf "Directory %s missing; skip\n" "$cdir" 1>&2
+			printf "Dir '%s' missing; skip clean\n" "$cdir" 1>&2
 			return 1
 		fi
 		x_ ./update trees -f "$project" "$target"
